# Generated by Django 6.0.3 on 2026-03-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, choices=[('donor', 'Donor'), ('doctor', 'Doctor'), ('hospital', 'Hospital'), ('admin', 'Admin')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
