# Generated by Django 6.0.3 on 2026-04-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bloodpacket_bloodrequest_doctor_hospital_bloodusage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('fit', 'Fit'), ('not_fit', 'Not Fit')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
            ],
        ),
    ]
