# Generated by Django 6.0.3 on 2026-04-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notificationuser_bloodrequest_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notificationuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='notification_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
