# Generated by Django 6.0.3 on 2026-04-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_notificationuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to='api.user'),
        ),
        migrations.CreateModel(
            name='RequestAccept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_donations', to='api.user')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodrequest')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='api.user')),
            ],
        ),
    ]
