# Generated by Django 6.0.3 on 2026-04-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_donor_user_requestaccept'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='requester_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='sender_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
