# Generated by Django 6.0.3 on 2026-04-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_doctor_status_hospital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='code_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='code_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
