# Generated by Django 6.0.3 on 2026-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_doctor_code_id_hospital_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(default='Not Provide', max_length=255),
        ),
    ]
