# Generated by Django 6.0.3 on 2026-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_donor_district_donor_state_alter_donor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='district',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
