# Generated by Django 6.0.3 on 2026-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_doctor_district_doctor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
