# Generated by Django 6.0.3 on 2026-04-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_hospital_district_hospital_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='district',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='state',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
