# Generated by Django 6.0.3 on 2026-04-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_bloodrequest_district_bloodrequest_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
    ]
