# Generated by Django 6.0.3 on 2026-04-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_doctor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status2',
            field=models.CharField(choices=[('pending', 'Pending'), ('hospital_approved', 'Hospital Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
